# Cloudflare Workers configuration
name = "cursor-background-agents"
main = "src/worker.ts"
compatibility_date = "2025-07-01"


# Environment variables
[vars]
# Add any non-secret environment variables here

# D1 database for storing agents and webhook events
[[d1_databases]]
binding = "DB"
database_name = "cursor-agents-db"
database_id = "your-database-id"
