# Cloudflare Workers configuration
name = "discord-bot-webhook-receiver"
main = "src/worker.ts"
compatibility_date = "2025-07-01"

# Environment variables
[vars]
# Add any non-secret environment variables here

# KV namespace for storing interactions (optional)
# [[kv_namespaces]]
# binding = "INTERACTIONS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"